#!/bin/bash
# ssh-multi
# D.Kovalov
# https://gist.github.com/dmytro/3984680
# Based on http://linuxpixies.blogspot.jp/2011/06/tmux-copy-mode-and-how-to-control.html
 
# a script to ssh multiple servers over multiple tmux panes
 
 
starttmux() {
    if [ -z "$HOSTS" ]; then
       echo -n "Please provide of list of hosts separated by spaces [ENTER]: "
       read HOSTS
    fi
 
    local hosts=( $HOSTS )
 
 
    tmux new-window "ssh ${hosts[0]}"
    unset hosts[0];
    for i in "${hosts[@]}"; do
        tmux split-window -v "ssh $i"
        # s/tiled/even-vertical/
        tmux select-layout tiled > /dev/null
    done
    tmux select-pane -t 0
    tmux set-window-option synchronize-panes on > /dev/null
 
}
 
HOSTS=${HOSTS:=$*}
 
starttmux
